In [1]:
import numpy as np

In [2]:
a=np.arrange(15).reshape(3,5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [3]:
a=np.arange(15).reshape(3,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.size

15

In [6]:
a.ndim

2

In [7]:
a.shape

(3, 5)

In [8]:
n.dtype

NameError: name 'n' is not defined

In [9]:
a.dtype

dtype('int64')

In [10]:
a.dtype.name

'int64'

In [11]:
a.itemsize

8

In [12]:
b=np.array([2,3,4,5])

In [13]:
b

array([2, 3, 4, 5])

In [14]:
type(a)

numpy.ndarray

In [16]:
c = np.array([1,2],[3,4])

TypeError: data type not understood

In [17]:
np.array((1,2),93,4)

ValueError: only 2 non-keyword arguments accepted

In [18]:
np.array((1,2),(3,4))

TypeError: data type not understood

In [19]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [20]:
np.array([[1,2],[3,4]],dtype=complex)

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [21]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [23]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
np.ones((2,3),dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [25]:
np.empty((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [26]:
np.empty((5,4))

array([[  6.93941437e-310,   2.86706057e-316,   0.00000000e+000,
          6.93938401e-310],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          6.93941154e-310],
       [  0.00000000e+000,   0.00000000e+000,   6.93938420e-310,
          6.93938403e-310],
       [  7.11454530e-322,   2.42092166e-322,   6.93941437e-310,
          1.63041663e-322]])

In [27]:
np.arrange(10,20,2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [28]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [29]:
np.linspace(1,2,2)

array([ 1.,  2.])

In [30]:
from numpy import pi

In [31]:
np.linspace(2,pi,9)

array([ 2.        ,  2.14269908,  2.28539816,  2.42809725,  2.57079633,
        2.71349541,  2.85619449,  2.99889357,  3.14159265])

In [33]:
np.sin(np.linspace(0,3,3))

array([ 0.        ,  0.99749499,  0.14112001])

In [34]:
a=np.arange(5)

In [35]:
print(a)

[0 1 2 3 4]


In [36]:
print(np.arange(1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [37]:
a=np.arange(5)

In [38]:
b=np.array([4,6,2,8,9])

In [39]:
a-b

array([-4, -5,  0, -5, -5])

In [40]:
a**2

array([ 0,  1,  4,  9, 16])

In [41]:
a<=5

array([ True,  True,  True,  True,  True], dtype=bool)

In [42]:
a<2

array([ True,  True, False, False, False], dtype=bool)

In [43]:
a=np.array([[1,2],[3,4]])

In [44]:
b=np.array([[2,7],[6,9]])

In [45]:
a*b

array([[ 2, 14],
       [18, 36]])

In [46]:
a.dot(b)

array([[14, 25],
       [30, 57]])

In [47]:
np.dot(a,b)

array([[14, 25],
       [30, 57]])

In [48]:
np.random.random((3,4))

array([[ 0.33378389,  0.14852408,  0.52452899,  0.74738297],
       [ 0.11511383,  0.14952323,  0.49992166,  0.63293566],
       [ 0.60677157,  0.82462582,  0.11959394,  0.60955752]])

In [49]:
a+=3

In [50]:
a

array([[4, 5],
       [6, 7]])

In [51]:
a.sum

<function ndarray.sum>

In [52]:
a.sum()

22

In [53]:
a.min()

4

In [54]:
a.max()

7

In [55]:
a.max(axis=0)

array([6, 7])

In [56]:
a.cumsum

<function ndarray.cumsum>

In [57]:
a.cumsum()

array([ 4,  9, 15, 22])

In [58]:
a.cumsum(axis=0)

array([[ 4,  5],
       [10, 12]])

In [59]:
np.add(a,b)

array([[ 6, 12],
       [12, 16]])

In [60]:
np.exp(a)

array([[   54.59815003,   148.4131591 ],
       [  403.42879349,  1096.63315843]])

In [61]:
a=np.arange(10)

In [62]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a[7]
a[:6:2]
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [64]:
for i in a:
    print i

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-64-873d8ba6ec31>, line 2)

In [65]:
for i in a:
    print (i)

0
1
2
3
4
5
6
7
8
9


In [66]:
def irr(a,b):
    return a+b
a = np.fromfunction(irr,(3,4))

In [67]:
a

array([[ 0.,  1.,  2.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 2.,  3.,  4.,  5.]])

In [68]:
a[-1]

array([ 2.,  3.,  4.,  5.])

In [69]:
a = np.array([[[1],[2]],[[3],[4]]])

In [70]:
a

array([[[1],
        [2]],

       [[3],
        [4]]])

In [71]:
a[...,0]

array([[1, 2],
       [3, 4]])

In [72]:
for row in a:
    print a

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-72-4599a269d35e>, line 2)

In [73]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [74]:
for i in a:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [75]:
a.flat

In [76]:
for h in a.flat:
    print(h)

1
2
3
4
5
6
7
8


In [77]:
a.shape

(2, 4)

In [78]:
a.T.shape

(4, 2)

In [79]:
a.ravel.shape

AttributeError: 'builtin_function_or_method' object has no attribute 'shape'

In [80]:
a.ravel().shape

(8,)

In [81]:
a.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [82]:
a.resize(2,2,2)

In [83]:
a.shape

(2, 2, 2)

In [84]:
a.reshape(4,-1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
a=10*np.random.random((2,2))

In [86]:
b=10*np.random.random((2,2))

In [87]:
a

array([[ 6.4194348 ,  2.49766472],
       [ 1.85147216,  9.0708796 ]])

In [88]:
b

array([[ 5.81134902,  3.87886707],
       [ 4.75574356,  7.30808315]])

In [89]:
np.hstack(a,b)

TypeError: hstack() takes 1 positional argument but 2 were given

In [90]:
a.hstack(b)

AttributeError: 'numpy.ndarray' object has no attribute 'hstack'

In [7]:
import numpy as np
c = np.array([[2],[3]])
c.shape

(2, 1)

In [6]:
np.hstack([a,c])

array([[  9.12972142e+00,   7.74858732e-03,   2.00000000e+00],
       [  3.38666051e+00,   7.76383206e+00,   3.00000000e+00]])

In [92]:
np.vstack([a,b])

array([[ 6.4194348 ,  2.49766472],
       [ 1.85147216,  9.0708796 ],
       [ 5.81134902,  3.87886707],
       [ 4.75574356,  7.30808315]])

In [94]:
from numpy import newaxis
a = np.array([1,2])
b = np.array([3,4])
np.column_stack([a[:,newaxis],b[:,newaxis]])

array([[1, 3],
       [2, 4]])

In [95]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [96]:
np.c_[1:4,[0]]

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [97]:
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [98]:
np.hsplit(a,3)

ValueError: array split does not result in an equal division

In [99]:
a=np.hstack([a,np.array([[3],[6]])])

In [100]:
a

array([[1, 2, 3, 4, 5, 3],
       [6, 7, 8, 9, 0, 6]])

In [101]:
np.hsplit(a,3)

[array([[1, 2],
        [6, 7]]), array([[3, 4],
        [8, 9]]), array([[5, 3],
        [0, 6]])]

In [102]:
np.vsplit(a,1)

[array([[1, 2, 3, 4, 5, 3],
        [6, 7, 8, 9, 0, 6]])]

In [103]:
np.vsplit(a,2)

[array([[1, 2, 3, 4, 5, 3]]), array([[6, 7, 8, 9, 0, 6]])]

In [104]:
b=a

In [105]:
b is a

True

In [106]:
id(a)

140454695850032

In [107]:
id(b)

140454695850032

In [108]:
c = a.view

In [109]:
id(c)

140454699777912

In [110]:
c.base is a

AttributeError: 'builtin_function_or_method' object has no attribute 'base'

In [111]:
a.shape

(2, 6)

In [112]:
c.shape

AttributeError: 'builtin_function_or_method' object has no attribute 'shape'

In [113]:
c.flag.ownsdata

AttributeError: 'builtin_function_or_method' object has no attribute 'flag'

In [114]:
c = a.view

In [115]:
c.base is a

AttributeError: 'builtin_function_or_method' object has no attribute 'base'

In [116]:
c

<function ndarray.view>

In [117]:
print(c)

<built-in method view of numpy.ndarray object at 0x7fbe2840d030>


In [118]:
c=a.view()

In [119]:
c.base is a

True

In [120]:
c

array([[1, 2, 3, 4, 5, 3],
       [6, 7, 8, 9, 0, 6]])

In [121]:
c is a

False

In [122]:
c.shape

(2, 6)

In [123]:
c[0,0]=10

In [124]:
a

array([[10,  2,  3,  4,  5,  3],
       [ 6,  7,  8,  9,  0,  6]])

In [125]:
x=a.copy()

In [126]:
x[0,0]=0

In [127]:
a

array([[10,  2,  3,  4,  5,  3],
       [ 6,  7,  8,  9,  0,  6]])

In [131]:
a = np.arange(15)**2

In [129]:
i=np.array([[1,2],[5,6]])

In [132]:
a[i]

array([[ 1,  4],
       [25, 36]])

In [133]:
b = a>6

In [134]:
b

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True], dtype=bool)

In [135]:
a[b]

array([  9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196])

In [136]:
a = np.array([[1,2,3,4],[5,2,8,5],[1,8,5,3]])

In [137]:
a1 = np.array([False,True,True])

In [138]:
a2 = np.array([True,False,True,False])

In [139]:
a[a1,]

array([[5, 2, 8, 5],
       [1, 8, 5, 3]])

In [140]:
a[a1,a2]

array([5, 5])

In [141]:
a=np.array([1,2,5,8])

In [142]:
b=np.array([4,8,1])

In [143]:
c=np.array([1,2,3,4,5,6])

In [144]:
ax,bx,cx = np.ix_(a,b,c)

In [145]:
ax

array([[[1]],

       [[2]],

       [[5]],

       [[8]]])

In [146]:
bx

array([[[4],
        [8],
        [1]]])

In [147]:
cx

array([[[1, 2, 3, 4, 5, 6]]])

In [148]:
x = ax+bx*cx

In [149]:
x[1,0,4]

22

In [150]:
a[1]+b[0]*c[4]

22

In [151]:
a.transpose()

array([1, 2, 5, 8])

In [152]:
a.T

array([1, 2, 5, 8])

In [153]:
a=np.array([[1,2],[4,7]])

In [154]:
a.T

array([[1, 4],
       [2, 7]])

In [155]:
a

array([[1, 2],
       [4, 7]])

In [156]:
a.tranpose()

AttributeError: 'numpy.ndarray' object has no attribute 'tranpose'

In [157]:
a.transpose()

array([[1, 4],
       [2, 7]])

In [158]:
a

array([[1, 2],
       [4, 7]])

In [159]:
np.linalg.inv(a)

array([[-7.,  2.],
       [ 4., -1.]])

In [160]:
a.trace()

8

In [161]:
b = np.array([[1],[8]])

In [162]:
np.linalg.solve(a,b)

array([[ 9.],
       [-4.]])

In [163]:
a=np.arange(30).reshape(2,3,-1)

In [164]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])